In [1]:
import tensorflow as tf



# Background
### Plane Vectors
Vectors will often be introduced as column matrices
Plane vectors are the most straightforward setup of tensors and they exist in vector space.  
recall: Unit vectors have a magnitued of one and are used to express 2-d or 3-d vectors as sums of their orthogonal components vectors.
### Tensors
Vectors, along with covectors and linear operators, are specific cases of tensors.
A tensor is a mathematical representation of a physical entity that may be characterized by magnitude and multiple directions.
In n-dimensional space, scalars always require one number, vectors require n numbers, and tensors require n^R numbers (where R is the rank of the tensor).
A unique aspect of tensors is the ability to combine components and basis vectors. 
    Basis vectors transform one way between reference frames and the components transform in such a way as to keep the combination between components and basis vectors the same. 

### Value types that can be used in tensors:
1. Constants
Values that don't change
2. Placeholders
These are values that are unassigned and will be initialized by the session when it's run. It's a placeholder for a tensor.
3. Variables
Values that change.

In [7]:
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

result = tf.multiply(x1,x2)
print (result)

Tensor("Mul_5:0", shape=(4,), dtype=int32)


To see the result of the above code, you have to initialize an interactive session, then print the result of that session.

In the following two chunks of code, we define a default session.

In [9]:
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

result = tf.multiply(x1,x2)

sess = tf.Session()

print(sess.run(result))

sess.close()

[ 5 12 21 32]


In [11]:
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

result = tf.multiply(x1,x2)

with tf.Session() as sess:
        output = sess.run(result)
        print(output)

[ 5 12 21 32]


The following example is the same as above; however we're also modifying the session by logging the GPU or CPU device that is assigned to the operation. The tutorial doesn't say how to print this info.
This is just an example of how to customize a session.

You can use the following config. if you want to use soft constraints.

In [15]:
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

result = tf.multiply(x1,x2)

config = tf.ConfigProto(log_device_placement=True)

sess = tf.Session()

print(sess.run(result))

sess.close()

[ 5 12 21 32]


# Understanding Belgian Traffic Sign Data
1. Traffic signs are usually in Dutch and French
2. There are six categories of signs
    a. Warning
    b. Priority
    c. Prohibitory
    d. Mandatory
    e. Parking/stalling
    f. Designatory signs
3. on 01/01/17, 30k prohibitory speed related signs were removed from the roads.
4. The overwhelming presence of traffic signs in belgian has been an ongoing topic of discussion.

In [1]:
import os
def load_data(data_directory):
    directories = [d for d in os.listdir(data_directory)
                   if os.path.isdir(os.path.join(data_directory, d))]
    
    labels = []
    images = []
    
    for d in directories:
        label_directory = os.path.join(data_directory, d)
        file_names = [os.path.join(label_directory, f)
                     for f in os.listdir(label_directory)
                     if f.endswith(".ppm")]
        
        for f in files_names:
            images.append(skimage.data.imread(f))
            labels.append(int(d))
        return images, labels

# home/aroz108/BelgiumTSC_Testing.zip
    
ROOT_PATH = "/Users/atomi/Downloads/"
train_data_directory = os.path.join(ROOT_PATH, "TrafficSigns/Training")
test_data_directory = os.path.join(ROOT_PATH, "TrafficSigns/Testing")
    
images, labels = load_data(train_data_directory)

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/C/Users/atomi/Downloads/TrafficSigns/Training'

In [ ]:
C:\Users\atomi\Downloads\TrafficSigns\Training.zip